sudo: false

language: go

services:
  - docker

go:
- 1.11.x

env:
  global:
    - IMAGE_NAME=davidseyboldblog/todo-service
  matrix:
    - GO111MODULE=on
  

git:
  depth: 1

notifications:
  email: false

before_script:
  - docker pull "$IMAGE_NAME" || true
script:
  - go test -v -race ./...
  - docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" .
  
before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${TRAVIS_TAG}"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${TRAVIS_TAG}"
  on:
    branch: master
    tags: true